name: Fudan Daily GKJ

on:
  schedule:
    - cron: '12 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install beautifulsoup4 lxml requests
      - name: Run app
        run: python fudanDaily-gkj.py
        env:
          DEFAULT_PUSH_KEY: ${{ secrets.DEFAULT_PUSH_KEY }}
          USER_LIST: ${{ secrets.USER_LIST }}
          PAFD_RETRY: 3
